dist: trusty
language: node_js
cache:
  yarn: true
  directories:
  - node_modules
node_js:
  - '9'
install:
  - yarn install
jobs:
  include:
    - stage: test
      name: "Linter"
      script:
        - yarn build
        - yarn dev:lint
    - stage: test
      name: "Unit tests"
      script:
        - yarn build
        - yarn test:units
    - stage: test
      name: "Task tests"
      script:
        - yarn build
        - yarn test:tasks
    - stage: test
      name: "Gas benchmark"
      script:
        - yarn build
        - yarn test:gasbenchmark
