dist: trusty
language: node_js
cache: 
  yarn: true
  directories:
  - node_modules
node_js:
  - '9'
install:
  - yarn install
jobs:
  include:
    - stage: test
      script: 
        - yarn build
        - yarn dev:lint
    - stage: test
      script:
        - yarn build
        - yarn test
    - stage: test
      script:
        - yarn build
        - ./scripts/test_cli.sh
